var day = new Date();
// var hrs = day.getHours();
// var min = day.getMinutes();
// var sec = day.getSeconds();
// console.log(hrs);
// console.log(min);
// console.log(sec);
document.getElementById('hour').innerText = day.getHours();
document.getElementById('minute').innerText = day.getMinutes();
document.getElementById('second').innerText = day.getSeconds();
